// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUx_DZoWOHK3J-yIFdBAgX2zws3d75hlA',
    appId: '1:718186325517:web:f2d2d165e95916c8225744',
    messagingSenderId: '718186325517',
    projectId: 'auth-af261',
    authDomain: 'auth-af261.firebaseapp.com',
    storageBucket: 'auth-af261.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlTfD3ETuBOh-RJLUIByTunsq--SI-GdQ',
    appId: '1:718186325517:android:ff29134e94cf53fd225744',
    messagingSenderId: '718186325517',
    projectId: 'auth-af261',
    storageBucket: 'auth-af261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgb8oUJNpNOoKMkqUqyA-uAR8Q93s02EQ',
    appId: '1:718186325517:ios:4aa8306806a334fb225744',
    messagingSenderId: '718186325517',
    projectId: 'auth-af261',
    storageBucket: 'auth-af261.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgb8oUJNpNOoKMkqUqyA-uAR8Q93s02EQ',
    appId: '1:718186325517:ios:4aa8306806a334fb225744',
    messagingSenderId: '718186325517',
    projectId: 'auth-af261',
    storageBucket: 'auth-af261.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUx_DZoWOHK3J-yIFdBAgX2zws3d75hlA',
    appId: '1:718186325517:web:2d1ee191f38ba7cc225744',
    messagingSenderId: '718186325517',
    projectId: 'auth-af261',
    authDomain: 'auth-af261.firebaseapp.com',
    storageBucket: 'auth-af261.appspot.com',
  );
}
